version: '3'

services:
  db:
    image: postgres:alpine
    env_file:
      - ./server/.env
    ports:
      - 5432:5432
  app:
    build: ./
    environment:
      POSTGRES_HOST: db
    command: bash -c "node build/scripts/syncTables.js && cd build && node index.js"
    depends_on:
      - db
    ports:
      - 5000:5000
