function sliderInput(n) {
  let result = ''
  for (let i = 0; i < n; i++) {
    result = result + '{rightarrow}'
  }
  return result
}

describe('Simulation Tab general tests', () => {
  const fileName = 'carbo2013.xml'

  before(() => {
    cy.visit('#/simulation')
      .get('[data-test="options"]')
      .click()
      .get('[data-test="importOption"]')
      .click()
      .fixture(fileName)
      .then(fileContent => {
        cy.get('input[type="file"]').upload({
          encoding: 'utf-8',
          fileContent,
          fileName,
          mimeType: 'application/xml',
        })
      })
      .get('[data-test="import-submit-button"]')
      .click()
  })

  it('Reactions populated', () => {
    cy.get('[data-test="reactions-table"]')
      .find('tbody')
      .find('tr')
  })

  it('Species correctly appear in the species panel', () => {
    cy.get('[data-test="reactions-table"]')
      .find('tbody')
      .find('tr')
      .first()
      .find('input')
      .check({ force: true })
      .get('[data-test="species-table"]')
      .find('tbody')
      .find('tr')
      .get('[data-test="reset-button"]')
      .click()
  })
})

describe('Simulation Tab non-reversible reaction tests', () => {
  const fileName = 'carbo2013.xml'

  before(() => {
    cy.visit('#/simulation')
      .get('[data-test="options"]')
      .click()
      .get('[data-test="importOption"]')
      .click()
      .fixture(fileName)
      .then(fileContent => {
        cy.get('input[type="file"]').upload({
          encoding: 'utf-8',
          fileContent,
          fileName,
          mimeType: 'application/xml',
        })
      })
      .get('[data-test="import-submit-button"]')
      .click()
  })

  it('Run mass action simulation', () => {
    cy.get('[data-test="reactions-table"]')
      .find('tbody')
      .find('tr')
      .first()
      .find('input')
      .check({ force: true })
      .get('select')
      .first()
      .select('mass-action')
      .get('[data-test="ratelaw-form"]')
      .find('input[type="number"]')
      .clear()
      .type(1)
      .get('[data-test="ratelaw-submit-button"]')
      .click()
      .get('[data-test="species-table"]')
      .find('tbody')
      .find('.specie-slider')
      .first()
      .find('.rc-slider-handle')
      .type(sliderInput(20))
      .get('[data-test="run-button"]')
      .click()
      .get('.Toastify')
      .contains('Simulation successful.')
      .get('[data-test="reset-button"]')
      .click()
  })

  it('Run reversible mass action simulation', () => {
    cy.get('[data-test="reactions-table"]')
      .find('tbody')
      .find('#reaction_23')
      .check({ force: true })
      .get('#reaction_23-select')
      .select('mass-action', { force: true })
      .get('[data-test="ratelaw-form"]')
      .find('input[type="number"]')
      .eq(0)
      .clear()
      .type(1)
      .get('[data-test="ratelaw-form"]')
      .find('input[type="number"]')
      .eq(1)
      .clear()
      .type(2)
      .get('[data-test="ratelaw-submit-button"]')
      .click()
      .get('[data-test="species-table"]')
      .find('tbody')
      .find('.specie-slider')
      .first()
      .find('.rc-slider-handle')
      .type(sliderInput(20))
      .get('[data-test="run-button"]')
      .click()
      .get('.Toastify')
      .contains('Simulation successful.')
      .get('[data-test="reset-button"]')
      .click()
  })

  it('Run michaelis-menten simulation', () => {
    cy.get('[data-test="reactions-table"]')
      .find('tbody')
      .find('tr')
      .first()
      .find('input')
      .check({ force: true })
      .get('select')
      .first()
      .select('michaelis-menten')
      .get('[data-test="ratelaw-form"]')
      .find('input[type="number"]')
      .eq(0)
      .clear()
      .type(1)
      .get('[data-test="ratelaw-form"]')
      .find('input[type="number"]')
      .eq(1)
      .clear()
      .type(1)
      .get('[data-test="ratelaw-submit-button"]')
      .click()
      .get('[data-test="species-table"]')
      .find('tbody')
      .find('.specie-slider')
      .first()
      .find('.rc-slider-handle')
      .type(sliderInput(20))
      .get('[data-test="run-button"]')
      .click()
      .get('.Toastify')
      .contains('Simulation successful.')
      .get('[data-test="reset-button"]')
      .click()
  })

  it('Run reversible michaelis menten simulation', () => {
    cy.get('[data-test="reactions-table"]')
      .find('tbody')
      .find('#reaction_23')
      .check({ force: true })
      .get('#reaction_23-select')
      .select('michaelis-menten', { force: true })
      .get('[data-test="ratelaw-form"]')
      .find('input[type="number"]')
      .eq(0)
      .clear()
      .type(1)
      .get('[data-test="ratelaw-form"]')
      .find('input[type="number"]')
      .eq(1)
      .clear()
      .type(2)
      .get('[data-test="ratelaw-form"]')
      .find('input[type="number"]')
      .eq(2)
      .clear()
      .type(3)
      .get('[data-test="ratelaw-form"]')
      .find('input[type="number"]')
      .eq(3)
      .clear()
      .type(4)
      .get('[data-test="ratelaw-submit-button"]')
      .click()
      .get('[data-test="species-table"]')
      .find('tbody')
      .find('.specie-slider')
      .first()
      .find('.rc-slider-handle')
      .type(sliderInput(20))
      .get('[data-test="run-button"]')
      .click()
      .get('.Toastify')
      .contains('Simulation successful.')
      .get('[data-test="reset-button"]')
      .click()
  })

  it('Run hill kinetics simulation', () => {
    cy.get('[data-test="reactions-table"]')
      .find('tbody')
      .find('tr')
      .first()
      .find('input')
      .check({ force: true })
      .get('select')
      .first()
      .select('hill-equation')
      .get('[data-test="ratelaw-form"]')
      .find('input[type="number"]')
      .eq(0)
      .clear()
      .type(1)
      .get('[data-test="ratelaw-form"]')
      .find('input[type="number"]')
      .eq(1)
      .clear()
      .type(1)
      .get('[data-test="ratelaw-form"]')
      .find('input[type="number"]')
      .eq(2)
      .clear()
      .type(2)
      .get('[data-test="ratelaw-submit-button"]')
      .click()
      .get('[data-test="species-table"]')
      .find('tbody')
      .find('.specie-slider')
      .first()
      .find('.rc-slider-handle')
      .type(sliderInput(20))
      .get('[data-test="run-button"]')
      .click()
      .get('.Toastify')
      .contains('Simulation successful.')
      .get('[data-test="reset-button"]')
      .click()
  })

  it('Run custom rate simulation', () => {
    cy.get('[data-test="reactions-table"]')
      .find('tbody')
      .find('tr')
      .first()
      .find('input')
      .check({ force: true })
      .get('select')
      .first()
      .select('custom-rate')
      .get('[data-test="ratelaw-form"]')
      .find('input[type="text"]')
      .type('0.5 * s2')
      .get('[data-test="ratelaw-submit-button"]')
      .click()
      .get('[data-test="species-table"]')
      .find('tbody')
      .find('.specie-slider')
      .first()
      .find('.rc-slider-handle')
      .type(sliderInput(20))
      .get('[data-test="run-button"]')
      .click()
      .get('.Toastify')
      .contains('Simulation successful.')
      .get('[data-test="reset-button"]')
      .click()
  })

  it('Run reversible custom rate simulation', () => {
    cy.get('[data-test="reactions-table"]')
      .find('tbody')
      .find('#reaction_23')
      .check({ force: true })
      .get('#reaction_23-select')
      .select('custom-rate')
      .get('[data-test="ratelaw-form"]')
      .find('input[type="text"]')
      .eq(0)
      .type('0.5 * species_1')
      .get('[data-test="ratelaw-form"]')
      .find('input[type="text"]')
      .eq(1)
      .type('0.3 * s4')
      .get('[data-test="ratelaw-submit-button"]')
      .click()
      .get('[data-test="species-table"]')
      .find('tbody')
      .find('.specie-slider')
      .first()
      .find('.rc-slider-handle')
      .type(sliderInput(20))
      .get('[data-test="run-button"]')
      .click()
      .get('.Toastify')
      .contains('Simulation successful.')
      .get('[data-test="reset-button"]')
      .click()
  })
})
